import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NavHeader from './components/Elements/NavHeader';
import NavFooter from './components/Elements/NavFooter';
import { wrapper } from "./store";
import {Provider} from 'react-redux';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Nevrycards',
  description: 'Generated by create next app',
}

function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
  
    <html lang="en">
    
      <body className={inter.className}>
   
     <NavHeader/>
     {children}
        {/* <NavFooter/> */}
    
        </body>

    </html>
 
  )
}
export default RootLayout;